# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-13 20:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scene',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('slug', models.SlugField(unique=True)),
                ('number', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12'), (13, '13'), (14, '14'), (15, '15'), (16, '16')])),
                ('house', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G'), ('H', 'H'), ('I', 'I'), ('J', 'J'), ('K', 'K'), ('L', 'L'), ('M', 'M'), ('N', 'N'), ('O', 'O'), ('P', 'P')], default='M', max_length=1)),
                ('dimmable', models.BooleanField(default=False)),
                ('order', models.PositiveSmallIntegerField(db_index=True, default=0, editable=False)),
                ('state', models.BooleanField(default=False)),
                ('auto_managed', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('order',),
                'permissions': (('view_unit', 'Can view unit'),),
            },
        ),
        migrations.AddField(
            model_name='scene',
            name='units',
            field=models.ManyToManyField(to='core.Unit'),
        ),
    ]
