# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-17 22:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20171114_0011'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolarSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(choices=[('dawn_astronomical', 'Dawn Astronomical'), ('dawn_nautical', 'Dawn Nautical'), ('dawn_civil', 'Dawn Civil'), ('sunrise', 'Sunrise'), ('solar_noon', 'Solar Noon'), ('sunset', 'Sunset'), ('dusk_civil', 'Dusk Civil'), ('dusk_nautical', 'Dusk Nautical'), ('dusk_astronomical', 'Dusk Astronomical')], help_text='Solar event type', max_length=18, unique=True)),
            ],
            options={
                'ordering': ('event',),
            },
        ),
        migrations.AddField(
            model_name='unit',
            name='off_schedules',
            field=models.ManyToManyField(blank=True, help_text='Automatic schedules to turn off the unit.', related_name='off_unit_set', to='core.SolarSchedule'),
        ),
        migrations.AddField(
            model_name='unit',
            name='on_schedules',
            field=models.ManyToManyField(blank=True, help_text='Automatic schedules to turn on the unit.', related_name='on_unit_set', to='core.SolarSchedule'),
        ),
    ]
