# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-19 05:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20171117_1739'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crontab', models.CharField(help_text='Crontab entry', max_length=64, unique=True)),
            ],
        ),
    ]
