# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-19 05:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='off_solar_schedules',
            field=models.ManyToManyField(blank=True, help_text='Automatic solar schedules to turn off the unit.', related_name='off_unit_set', to='core.SolarSchedule'),
        ),
        migrations.AddField(
            model_name='unit',
            name='on_solar_schedules',
            field=models.ManyToManyField(blank=True, help_text='Automatic solar schedules to turn on the unit.', related_name='on_unit_set', to='core.SolarSchedule'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='off_schedules',
            field=models.ManyToManyField(blank=True, help_text='Automatic schedules to turn off the unit.', related_name='off_unit_set', to='core.Schedule'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='on_schedules',
            field=models.ManyToManyField(blank=True, help_text='Automatic schedules to turn on the unit.', related_name='on_unit_set', to='core.Schedule'),
        ),
    ]
