# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-26 15:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0005_auto_20171119_0038'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersistentToken',
            fields=[
                ('key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='persistent_auth_token', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
