# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 18:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_persistenttoken'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unit',
            options={'ordering': ('order',)},
        ),
    ]
