# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 17:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20171127_1328'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unit',
            name='off_schedules',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='off_solar_schedules',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='on_schedules',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='on_solar_schedules',
        ),
    ]
