# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 20:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20171128_1215'),
    ]

    operations = [
        migrations.CreateModel(
            name='OffScheduleConstraint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('if_home', models.BooleanField(default=False, help_text='Only use this schedule if a real person is home')),
                ('schedule', models.ForeignKey(help_text='The schedule object for this relationship', on_delete=django.db.models.deletion.CASCADE, to='core.Schedule')),
                ('unit', models.ForeignKey(help_text='The unit object for this relationship', on_delete=django.db.models.deletion.CASCADE, to='core.Unit')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OffSolarScheduleConstraint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('if_home', models.BooleanField(default=False, help_text='Only use this schedule if a real person is home')),
                ('solarschedule', models.ForeignKey(help_text='The solar schedule object for this relationship', on_delete=django.db.models.deletion.CASCADE, to='core.SolarSchedule')),
                ('unit', models.ForeignKey(help_text='The unit object for this relationship', on_delete=django.db.models.deletion.CASCADE, to='core.Unit')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OnScheduleConstraint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('if_home', models.BooleanField(default=False, help_text='Only use this schedule if a real person is home')),
                ('schedule', models.ForeignKey(help_text='The schedule object for this relationship', on_delete=django.db.models.deletion.CASCADE, to='core.Schedule')),
                ('unit', models.ForeignKey(help_text='The unit object for this relationship', on_delete=django.db.models.deletion.CASCADE, to='core.Unit')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OnSolarScheduleConstraint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('if_home', models.BooleanField(default=False, help_text='Only use this schedule if a real person is home')),
                ('solarschedule', models.ForeignKey(help_text='The solar schedule object for this relationship', on_delete=django.db.models.deletion.CASCADE, to='core.SolarSchedule')),
                ('unit', models.ForeignKey(help_text='The unit object for this relationship', on_delete=django.db.models.deletion.CASCADE, to='core.Unit')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='unit',
            name='off_schedules',
            field=models.ManyToManyField(blank=True, help_text='Automatic schedules to turn off the unit.', related_name='off_unit_set', through='core.OffScheduleConstraint', to='core.Schedule'),
        ),
        migrations.AddField(
            model_name='unit',
            name='off_solar_schedules',
            field=models.ManyToManyField(blank=True, help_text='Automatic solar schedules to turn off the unit.', related_name='off_unit_set', through='core.OffSolarScheduleConstraint', to='core.SolarSchedule'),
        ),
        migrations.AddField(
            model_name='unit',
            name='on_schedules',
            field=models.ManyToManyField(blank=True, help_text='Automatic schedules to turn on the unit.', related_name='on_unit_set', through='core.OnScheduleConstraint', to='core.Schedule'),
        ),
        migrations.AddField(
            model_name='unit',
            name='on_solar_schedules',
            field=models.ManyToManyField(blank=True, help_text='Automatic solar schedules to turn on the unit.', related_name='on_unit_set', through='core.OnSolarScheduleConstraint', to='core.SolarSchedule'),
        ),
        migrations.AlterUniqueTogether(
            name='onsolarscheduleconstraint',
            unique_together=set([('solarschedule', 'unit')]),
        ),
        migrations.AlterUniqueTogether(
            name='onscheduleconstraint',
            unique_together=set([('schedule', 'unit')]),
        ),
        migrations.AlterUniqueTogether(
            name='offsolarscheduleconstraint',
            unique_together=set([('solarschedule', 'unit')]),
        ),
        migrations.AlterUniqueTogether(
            name='offscheduleconstraint',
            unique_together=set([('schedule', 'unit')]),
        ),
    ]
